#datasource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scada?characterEncoding=utf-8&amp;useUnicode=true&amp;autoReconnect=true
    data-username: scada
    data-password: scada
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
 
    


#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/scada?characterEncoding=utf-8&amp;useUnicode=true&amp;autoReconnect=true
#spring.datasource.username=scada
#spring.datasource.password=scada

#jpa configuration
#spring.jpa.show-sql=true
#spring.jpa.database=mysql
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect